### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rickstuart92**

### CODE REVIEW

**Comment by ahaile5** [comment]
Code Review posted

**Review by ahaile5 — APPROVED** [review]
Function Header Comment Block
•	There is no change record in the header comment section.
•	Most of the functions have short explanations. The description shows the purpose of the function. However, not all functions have a description.  All functions need to have a header comment block.
•	There is an explanation of parameters and return types.
Code 
•	When there is a descriptive comment for the line of code, it is accurate and informative but not all code blocks have descriptive comments.
•	Error returns properly handled and not disregarded. 
•	Constants are not hardcoded.
•	The variable names are distinct and descriptive.
•	All code performs the intended function.
•	  There is no redundant code.
•	The overall code is not complicated.

**Comment by AlbertoBonfiglio** [comment]
The documents are functional and reflect the latest edition with the corrections suggested and/or requested by the professor

**Review by AlbertoBonfiglio — APPROVED** [review]
The documents are functional and reflect the latest edition with the corrections suggested and/or requested by the professor

**Pull request merged**
